### ISSUE TITLE
deploy command of neon-cli accepts an extra argument "caller".  

### ISSUE THREAD

**Issue by sinev-valentine** [Cyber-Core/solana-program-library#271]
depoy command of neon-cli accepts an argument "caller". It is an extra argument, because caller must be calculated from ethereum address of ethereum signer.

Evm-loader checks for compliance caller and recovered_address from trx :
https://github.com/neonlabsorg/neon-evm/blob/develop/evm_loader/program/src/entrypoint.rs#L998

Dublicate https://app.zenhub.com/workspaces/solana-evm-6007c75a9dc141001100ccb8/issues/neonlabsorg/neon-evm/252

**Comment by s-medvedev** [comment]
Duplicate neonlabsorg/neon-evm#252
